Tiny_links/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('links.urls'))
]

links/urls.py
from django.urls import path

from . import views

app_name = 'links'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.CreateView.as_view(), name='new'),
    path('<int:link_id>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.create_tiny_link, name='create'),
    path('links/<str:tiny_link>/', views.open_tiny_link, name='open'),
    path('delete/<int:link_id>/', views.delete_tiny_link, name='delete'),
]

links/models.py
from django.db import models


class Link(models.Model):
    orig_link = models.CharField(max_length=200)
    tiny_link = models.CharField(max_length=50, unique=True)
    follow_quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.tiny_link

links/views.py
import hashlib
import uuid

import bcrypt as bcrypt
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Link


class IndexView(generic.ListView):
    template_name = 'links/index.html'
    context_object_name = 'links_list'

    def get_queryset(self):
        return Link.objects.filter().order_by('-follow_quantity')


class CreateView(generic.CreateView):
    template_name = 'links/new.html'
    model = Link
    fields = ['orig_link']


class DetailView(generic.DetailView):
    model = Link
    pk_url_kwarg = 'link_id'
    template_name = 'links/detail.html'


def get_tiny_link(orig_link):
    tiny_link = bcrypt.hashpw(orig_link.encode('utf-8'), bcrypt.gensalt())
    return tiny_link.decode("utf-8")[40:50].replace('/', '')


def create_tiny_link(request):
    orig_link = request.POST['orig_link']
    link = Link.objects.create(
        orig_link=orig_link,
        tiny_link=get_tiny_link(orig_link=orig_link)
    )
    link.save()
    return HttpResponseRedirect(reverse('links:detail', args=(link.id,)))


def open_tiny_link(request, tiny_link):
    link = get_object_or_404(Link, tiny_link=tiny_link)
    orig_link = link.orig_link
    link.follow_quantity += 1
    link.save()
    return HttpResponseRedirect(orig_link)


def delete_tiny_link(request, link_id):
    link = get_object_or_404(Link, id=link_id)
    link.delete()
    return HttpResponseRedirect(reverse('links:index'))

links/templates/links/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    {% block style %}
        <link rel="stylesheet" type="text/css" href="{% static "fontawesome/css/all.min.css" %}" />
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'links/style.css' %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Tiny links</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

links/templates/links/detail.html
{% extends 'links/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="row">
        <a href="{% url 'links:index' %}" class="btn btn-primary">
            <i class="fas fa-align-left"></i>
            All links
        </a>
        <a href="{% url 'links:new' %}" class="btn btn-outline-primary">
            <i class="fas fa-plus"></i>
            Create new tiny link
        </a>
    </div>
    <h1 class="mt-2">Created tiny link</h1>
    <hr class="mt-0 mb-4">
    <div class="card" id="card-shadow">
        <div class="card-header">
            <span class="badge badge-info">
                <h5>
                    {{ link.orig_link }}
                </h5>
            </span>
            <p class="font-weight-normal">was opened {{ link.follow_quantity }} times</p>
        </div>
        <div class="card-body">
            <a class="card-title"
               href="http://127.0.0.1:8000/links/{{ link.tiny_link }}">http://127.0.0.1:8000/links/{{ link.tiny_link }}</a>
            <a href="{% url 'links:open' link.tiny_link %}" class="btn btn-primary">
                Open link
            </a>
            <a href="{% url 'links:delete' link.id %}" class="btn btn-danger">
                DELETE
            </a>
        </div>
    </div>
{% endblock %}

links/templates/links/index.html
{% extends 'links/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="row">
        <a href="{% url 'links:new' %}" class="btn btn-outline-primary">
            <i class="fas fa-plus"></i>
            Create new tiny link
        </a>
    </div>
    <div class="justify-content-center">
        <h1 class="mt-2">All links</h1>
    </div>
    <hr class="mt-0 mb-4">
    {% if links_list %}
        <ul class="justify-content-center">
            {% for link in links_list %}
                <li>
                    <div class="card" id="card-shadow">
                        <div class="card-header">
                            <span class="badge badge-info">
                                <h5>
                                    {{ link.orig_link }}
                                </h5>
                            </span>
                            <p class="font-weight-normal">was opened {{ link.follow_quantity }} times</p>
                        </div>
                        <div class="card-body">
                            <a class="card-title" href="http://127.0.0.1:8000/links/{{ link.tiny_link }}">http://127.0.0.1:8000/links/{{ link.tiny_link }}</a>
                            <a href="{% url 'links:open' link.tiny_link %}" class="btn btn-primary">
                                <i class="fas fa-link"></i>
                                OPEN LINK
                            </a>
                            <a href="{% url 'links:delete' link.id %}" class="btn btn-danger">
                                <i class="far fa-trash-alt"></i>
                                DELETE
                            </a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No tiny links are available</p>
    {% endif %}
{% endblock %}
</body>
</html>

links/templates/links/new.html
{% extends 'links/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <a href="{% url 'links:index' %}" class="btn btn-primary">
        <i class="fas fa-align-left"></i>
        All links
    </a>
    <h1 class="mt-2">New tiny link</h1>
    <hr class="mt-0 mb-4">
    <form
            method="post"
            novalidate
            action="{% url 'links:create' %}"
    >
        {% csrf_token %}
        {{ form.orig_link }}
        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock %}
</body>
</html>